DX-5: Added template react, , add and initialize checkout
DUNA-E-Commmerce/deuna-samples pull request #5
Opened 2022-11-03 17:37 UTC by iveJuarez

### Interfaces changes:

- directory for react template is added.
- Checkout is integrated with key secret.

### Ticket:
[DX-5](https://deuna.atlassian.net/browse/DX-5?atlOrigin=eyJpIjoiNTZiMWZiMzVjNzY0NDcyMjgyZTg1MjUxNTU4NmZhMDUiLCJwIjoiaiJ9)

2022-11-10 18:42 UTC, DiegoGallegos4 commented on checkout-widget-react/src/App.js
> +      const response = await fetch("http://localhost:3000/tokenizeOrder", {
La url debe una variable de ambiente.

2022-11-10 20:09 UTC, capdilla approved these changes

2022-11-10 20:18 UTC, Proskynete reviewed
Deje algunos comentarios

2022-11-18 20:19 UTC, yacodev commented
@iveJuarez  no deberíamos eliminar los archivos innecesarios que genera el create-react-app (por ejemplo los imágenes de react y el archivos de testing).
Al momento de modificar en la vista el JSON, no se están cogiendo los cambios  para payload que se envía a backend.

2022-11-18 21:17 UTC, yacodev requested changes
@iveJuarez no deberíamos eliminar los archivos innecesarios que genera el create-react-app (por ejemplo los imágenes de react y el archivos de testing).
Al momento de modificar en la vista el JSON, no se están cogiendo los cambios para payload que se envía a backend.

2022-11-22 18:29 UTC, yacodev approved these changes
🙌🏼

2022-11-28 20:41 UTC, merged