DX-63: Added template react for SDK2
DUNA-E-Commmerce/deuna-samples pull request #7
Opened 2022-11-22 17:19 UTC by iveJuarez

### Interfaces changes:

- Added directory for react template with SDK2.
- Checkout is integrated with public key.

![image](https://user-images.githubusercontent.com/112917159/203379196-a942e0e0-36f0-4112-9255-6fcb7ccabad5.png)

### Ticket:
[DX-63](https://deuna.atlassian.net/browse/DX-63?atlOrigin=eyJpIjoiYmQ0NzNmZDAzNmMwNDA3OTk1MDAzYThlMjVjN2EyNDIiLCJwIjoiaiJ9)

2022-11-22 18:27 UTC, yacodev requested changes

2022-11-22 18:27 UTC, yacodev commented on checkout-sdk2-react/src/.env
> +ENVIRONMENT=staging
el archivo `.env` debería  incluido en el repositorio, solo deberíamos mostrar un archivo  `.env.sample` con  la referencia de las variables de entorno.

2022-11-24 12:36 UTC, sabustamante commented on checkout-sdk2-react/src/mocks/mockOrder.json
> +      "phone": "+52617014458",
No usaría datos verdaderos de personas de DEUNA, veo varios datos sensibles, como email, nombre y teléfono.

2022-11-24 12:36 UTC, sabustamante commented on checkout-sdk2-react/src/mocks/mockPayment.json
> +  "email": "cpadilla@getduna.com",
No usaría datos verdaderos de personas de DEUNA, veo varios datos sensibles, como email, nombre y teléfono.

2022-11-30 17:09 UTC, sabustamante approved these changes

2022-11-30 18:44 UTC, merged